version: '3'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.22
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - ./mysql.cnf:/etc/my.cnf 
      - c:\xampp\mysql:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: tabela123
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass1234
      MYSQL_DATABASE: gene-task
  #Loadbalancer
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./nginx/ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    restart: always

  api:
    build: ./src
    ports:
      - '5000'
    restart: always
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database