version: '3.2'

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.22
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    #Specify Environment Variables for mysql
    environment:
      MYSQL_ROOT_PASSWORD: example1234

  #Adminer, to set MySQL with user and table
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #API web server
  api:
    #container_name: api
    build: ../src
    ports:
      - "80:5000"
    restart: always
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_URLS=http://+:5000
    #Name our custom api image
    image: api:latest
    #Deploy with three replicas in the case one of the containers fails (only in Docker Swarm)
    deploy:
      mode: replicated
      replicas: 2